project:
  type: book

book:
  title: "Data Mining with Python"
  author: "Youngrok Lee"
  date: today
  chapters:
    - index.qmd
    - ch02_regression.qmd
    - ch03_regularized_regression.qmd

format:
  html:
    theme: cosmo



